# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

commands:

  install-base-dependencies:
    description: Install dependencies for our app
    steps:
      - run:
          name: Install dependencies
          command: |
            make install
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint

jobs:

  build:
    docker:
      - image: ewkoch3/base:test
    working_directory: ~/repo
    steps:
      - checkout
      - install-base-dependencies
      - run:
          name: run lint
          command: |
            pip3 install pylint
            make lint
  
  test:
    docker:
      - image: ewkoch3/base:test
    working_directory: ~/repo
    steps:
      - checkout
      - install-base-dependencies
      - run:
          name: run tests
          command: |
            pip3 install pytest pytest-mock
            make test

workflows:
  default:
    jobs:
      - build
      - test
          requires: [build]