---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clustering-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: clustering-$COLOR_ACTIVE
                port: 
                  number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: clustering-service-main
spec:
  type: LoadBalancer
  selector:
    app: clustering-$COLOR_ACTIVE
    color: $COLOR_ACTIVE
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: clustering-service-test
spec:
  type: LoadBalancer
  selector:
    app: clustering-$COLOR_TEST
    color: $COLOR_TEST
  ports:
    - port: 80
      targetPort: 80